"use client"; 
import localFont from "next/font/local";
import "./globals.css";
import { useState, useEffect } from "react";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {


  const [date, setDate] = useState('');
  
  useEffect(() => {
    const today = new Date();
    const options = { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' };
    setDate(today.toLocaleDateString(undefined, options));
  }, []);

  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <header>

          <h1>To do App</h1>

        <h2 className="wellcomeMessage">Bem vindo!!!</h2>

        <div>
          <span>{date}</span>
        </div>
        </header>

        <main>{children}</main>

        <footer>
    <span>
        Projeto desenvolvido por <strong>Samuel Sousa</strong>
    </span>
    
    <div>
        <a href="https://github.com/samuelgsousa" target="_blank">GitHub <img src="./external-link.svg" alt="" class="external" />  <img src="./github-mark.svg" alt="GitHub" id="Github"/></a> 
        <a href="https://www.linkedin.com/in/samuel-gomes-teixeira-de-sousa-5537b71b9" target="_blank">Linkedin <img src="./external-link.svg" alt="Linkedin" class="external"/> <img src="./linkedin.svg" alt="" /> </a> 
    </div>
    
</footer>
      </body>
    </html>
  );
}
